### ISSUE TITLE
Clarification on usage

### ISSUE THREAD

**Issue by fromKolkata** [mgp25/Telegram-Bot-API#1]
Hi I saw this API just now. But I am a little confused how to use it. I read the wiki but cannot understand how to "start a conversation with @botfather". Also I cannot understand what is chat_id and how to get it. Also do I need to provide my phone number is this API for authentication? Please explain. Thank you

**Comment by mgp25** [comment]
@fromKolkata i just added a self-explanatory image in the wiki.

`chat_id` id the chat id, you will get it when someone talks to your bot, use `pollUpdates` to get any info/update your bot receives

I'll add more info to the wiki.

Regards
