### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by p031985s** [mgp25/Telegram-Bot-API#11]
Hi there, i just downloaded your Api but...

What is Token or where can i find it?

I have App api_id, App api_hash, Public keys but i cannot find it.

Can you help me.

Thank you.

**Comment by mgp25** [comment]
@p031985s this is for telegram you know? https://github.com/mgp25/Telegram-Bot-API/wiki/Setup-guide

**Comment by p031985s** [comment]
Thank you, it helps me a lot, i was trying to get token from their web. it is working now.
