### ISSUE TITLE
 Uncaught exception 'PDOException' 

### ISSUE THREAD

**Issue by adrianf29** [mgp25/Telegram-Bot-API#16]
hi iam follow your tutorial, i am developing on hosting server...
but get problem on  Uncaught exception 'PDOException' 

here is the error response of server.

: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: contacts' in /home/test/public_html/Telegram-Bot-API-master/examples/quoteBot.php:61 Stack trace: #0 /home/test/public_html/Telegram-Bot-API-master/examples/quoteBot.php(61): PDO->prepare('SELECT chat_id ...') #1 /home/test/public_html/Telegram-Bot-API-master/examples/quoteBot.php(25): addContact(115906090) #2 {main} thrown in /home/test/public_html/Telegram-Bot-API-master/examples/quoteBot.php on line 61

how can i fix it? thanks

**Comment by mgp25** [comment]
@adrianf29 General error: 1 no such table: contacts. 

Just create table contacts

Regards

**Comment by adrianf29** [comment]
done, but i got this error again.

Warning: file_get_contents(https://api.telegram.org/bot161837874:*****Ow006DpCxvq4Ee0lkQS5gf_rF***/sendMessage?chat_id=1159*****&disable_web_page_preview=0): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /home/test/public_html/Telegram-Bot-API-master/src/Telegram.php on line 420

the line error is " return json_decode(file_get_contents($this->baseURL . $method . '?' . http_build_query($params)), true); " ??

**Comment by mgp25** [comment]
@adrianf29 look at your url:

https://api.telegram.org/bot161837874:*****Ow006DpCxvq4Ee0lkQS5gf_rF***/sendMessage?chat_id=1159*****&disable_web_page_preview=0

it should be:

https://api.telegram.org/bot/161837874:*****Ow006DpCxvq4Ee0lkQS5gf_rF***/sendMessage?chat_id=1159*****&disable_web_page_preview=0)

Notice the `/` just after bot

Regards

**Comment by mgp25** [comment]
@adrianf29 weird, you are having an issue when trying to send the information via GET. Try retrying, im not sure whats happening there. I recommend you if possible to test it first locally (in your computer)

Regards

**Comment by adrianf29** [comment]
@mgp25 hemh sou you means i should run it first from my local computer? i used xampp.. is it works?

**Comment by adrianf29** [comment]
@mgp25 got many errors on localhost , :( why bot cant running on my host server

whereas in the script above ,
already have chat id but why can not running

**Comment by mgp25** [comment]
@adrianf29 i saw the error, look: https://github.com/mgp25/Telegram-Bot-API/blob/master/src/Telegram.php#L69

Change your script and use this instead:

``` php
$tg->sendMessage($chat_id, $text);
```

Where `$text` contains the message you want to send.

Regards

**Comment by adrianf29** [comment]
@mgp25 nice it works, thanks!

there's one thing, i run the webhook with setwebhook and response is {"ok":true,"result":true,"description":"Webhook was set"}

but its not working, why?

**Comment by mgp25** [comment]
@adrianf29 check this for more information in webhooks: https://core.telegram.org/bots/api

Regards

**Comment by adrianf29** [comment]
@mgp25 nice thank you very much
