### ISSUE TITLE
Send photo is not working

### ISSUE THREAD

**Issue by estoyarto** [mgp25/Telegram-Bot-API#17]
Hi, Im trying to use the api to send a picture, but is not working correctly. I try a local file on the server on the same place as the script, in anotehr folder or directly the url to the image getting the same result.
My test page looks like this:

require 'Telegram.php';
// initialise variables here
    $chat_id = "9999999";

$token = "11111111111:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";  // HERE YOUR TOKEN
//////////////////////////////////////////////////
echo "-#################################### \n ";
echo "#          Telegram CLIENT         # \n ";
echo "####################################- \n \n";

$tg = new telegramBot($token);

echo "Get Bot Information:\n";
$updates = $tg->getMe();
echo json_encode($updates) . "\n"; //<-- all ok

$tg->sendMessage($chat_id, "Working?");//<-- text message ok
$tg->sendChatAction($chat_id, 'upload_photo');//<-- action its ok

$tg->sendPhoto($chat_id, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/718smiley.png/220px-718smiley.png'); //<-- nothing happend / local file same result

**Comment by iimnd** [comment]
up

**Comment by inxomnyaa** [comment]
https://github.com/mgp25/Telegram-Bot-API/issues/3, maybe?
