### ISSUE TITLE
Add CURLOPT_RETURNTRANSFER to uploadFile()

### ISSUE THREAD

**Issue by virtualart-online** [mgp25/Telegram-Bot-API#20]
I suggest to add 

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

to the function uploadFile(). Otherwhise the message data (id. etc) will not be returned by the CURL operation if CURLOPT_RETURNTRANSFER is not set to 1 by default in the PHP enviroment.

**Comment by mgp25** [comment]
@jokebattle3 send a pull request and ill merge it

Regards
