### ISSUE TITLE
Errors in forwardMessage, sendVoice, getUserProfilePhotos 

### ISSUE THREAD

**Issue by inxomnyaa** [mgp25/Telegram-Bot-API#25]
forwardMessage:
![image](https://cloud.githubusercontent.com/assets/8733998/22922622/cef8fe1a-f29e-11e6-8497-34bcae3fc76a.png)

sendVoice: (i guess supposed to be $audio)
![image](https://cloud.githubusercontent.com/assets/8733998/22922634/e280bebe-f29e-11e6-923e-af0d315deefe.png)

getUserProfilePhotos $param vs $params
![image](https://cloud.githubusercontent.com/assets/8733998/22922673/068eba72-f29f-11e6-8a03-75758413f5b3.png)

Those happen in the composer package.

sendVoice: (i guess supposed to be $audio)
![image](https://cloud.githubusercontent.com/assets/8733998/22922634/e280bebe-f29e-11e6-923e-af0d315deefe.png)

Happens in the src/Telegram.php

**Comment by inxomnyaa** [comment]
And this here is just a sidenote
![image](https://cloud.githubusercontent.com/assets/8733998/22922832/7e2d3748-f29f-11e6-80c3-b821ee26938a.png)

**Comment by mgp25** [comment]
Fixed + use code form master

Regards

**Comment by inxomnyaa** [comment]
Composer doesn't seem to pull the master branch, 👍 anyways ;)
