### ISSUE TITLE
method sendPhoto doesn't work

### ISSUE THREAD

**Issue by sm1372** [mgp25/Telegram-Bot-API#3]
Hello

method `sendPhoto()` NOT work. i first get `$chat_id` from message and after this, want to send single photo whit this syntax : 

``` php
$tg->sendPhoto($chat_id , 'http://i.investopedia.com/dimages/graphics/binary.jpg') ;
```

other things like `$tg`   and   `$chat_id`   and  `sendMessage()`  is OK but this method doesn't work

please help me!

**Comment by mgp25** [comment]
@sm1372 hi there, can you post the debug log? Sometimes, some images don't work using an URL, have you tried sending an already stored image?

Regards

**Comment by sm1372** [comment]
UH error is :  =>  `Class 'CurlFile' not found   .../src/Telegram.php`

php version is :  5.3.3

how can i handle this?!

**Comment by mgp25** [comment]
@sm1372 you need to install cURL and you will be ready to go!

Regards

**Comment by sm1372** [comment]
i have read that cURLFile is only for php5.5 or higher ... yes?

how can handle this?

**Comment by mgp25** [comment]
@sm1372 update your PHP version

**Comment by inxomnyaa** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/23024425/9befd09e-f45a-11e6-9887-e58852bc32a8.png)
I get the error too now, but curl is activated. Any ideas?

EDIT:
i tried 
`			file_get_contents("https://api.telegram.org/bot".$token."/sendVideo?chat_id=".$chatID."&video=http://stream1.gifsoup.com/view3/4618514/pewdiepie-banana-slap-o.gif");
`
and this worked just fine
