### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by 9px** [mgp25/Telegram-Bot-API#5]
hi. telegram [recently](https://core.telegram.org/bots/api#making-requests-when-getting-updates) add an ability to perform a request to the telegram Bot API while sending an answer to the webhook.
can you do a simple implement of this feature in your bot?

**Comment by mgp25** [comment]
@9px sure, i'll do it this weekend, i'll tell you when it's ready

**Comment by 9px** [comment]
thanks. this issue also asked as question in [stackoverflow](http://stackoverflow.com/questions/32412519/how-perform-a-request-to-the-telegram-bot-api-while-sending-an-answer-to-the-web).

**Comment by mgp25** [comment]
@9px according to Telegram documentation: `It's not possible to know that such a request was successful or get its result.`

Test with yourself to check and check, but that should work although you don't receive any response.

Reference: https://core.telegram.org/bots/api#making-requests-when-getting-updates

Close this issue if this answered your question

Regards

**Comment by 9px** [comment]
No this is not answer.

When a user send a command to robot, robot (server) received it in 1 connection.
When we send an answer to the user (for example with `sendMessage` method), this is another connection and the telegram return a json so we can detect that the message sent successfully.

The link says that we can save 1 connection and use "answer to telegram webhook" to say the telegram that we want to send a message for example.
