### ISSUE TITLE
http request failed

### ISSUE THREAD

**Issue by moein-rahimi** [mgp25/Telegram-Bot-API#7]
hi i just used the getme and got this err:
 Warning: file_get_contents(https://api.telegram.org/bot<token>\getMe?): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway in C:\xampp\htdocs\testbot\vendor\mgp25\telegram-bot-api\src\Telegram.php on line 364

<?php

require "vendor/mgp25/telegram-bot-api/src/telegram.php";
$token = "<token>";
$tg = new TelegramBot($token);

$tg->getMe();

?>

**Comment by mgp25** [comment]
@moein-rahimi please, quote the code properly.

You haven't set a token, the token is required.

Regards
