### ISSUE TITLE
Typo on wiki + Update composer package

### ISSUE THREAD

**Issue by gojigeje** [mgp25/Telegram-Bot-API#9]
On https://github.com/mgp25/Telegram-Bot-API/wiki/Available-methods#constructor

``` php
$tg = new TelegramBot($token);
```

should be

``` php
$tg = new telegramBot($token); // small T
```

it can confuse a newbie like me :blush: 

also could you please update the composer package? thanks! :+1:

**Comment by mgp25** [comment]
@gojigeje fixed typo + composer package auto update it. 

Regards

**Comment by gojigeje** [comment]
maybe you should check it again:

``` sh
$ composer require mgp25/telegram-bot-api
```

my Telegram.php has no `getFile()` method from cedda6aa90b7eb001572a5695bf8108b66bed9ec.
CMIIW, I'm new to composer..

**Comment by mgp25** [comment]
@gojigeje now

Regards
